services:
  mysql:
    image: 'mysql:8.0.36'
    container_name: 'mysql'
    restart: 'always'
    environment:
      - 'MYSQL_ROOT_PASSWORD=support'
      - 'MYSQL_USER=support'
      - 'MYSQL_PASSWORD=support'
      - 'MYSQL_DATABASE=support'
    ports:
      - '3307:3306'
    volumes:
      - 'db-data:/var/lib/mysql'
    networks:
      - 'psa-network'

volumes:
  db-data: { }

networks:
    psa-network:
      external: true
